{{- if .Values.Dex.Type == "Ingress" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
{{- if .Values.Dex.Tls }}
  tls:
  - hosts:
    - echo.example.com
    secretName: echoserver-tls
{{- end }}
  rules:
  - host: echo.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: dex
{{- if .Values.Dex.Tls }}
          servicePort: 443
{{- else }}
          servicePort: 80
{{- end }}
{{- end }}
